### ISSUE TITLE
How to import a video from local disk

### ISSUE THREAD

**Issue by JannisWalkKIT** [scalabel/scalabel#240]
Hi,

i am struggling to import a video for instance segmentation tracking from my local disk. Could somebody provide a working example for this? 

Any help would be much appreciated!
Jannis

**Comment by fyu** [comment]
You can easily use our tools to set up the task.

The main data preparation tool is [prepare_data.py](https://github.com/scalabel/scalabel/blob/master/scalabel/tools/prepare_data.py). The doc is at https://www.scalabel.ai/doc/tools.html.

Assuming you are using the default config and the local images will be served from the folder `local-data/items` and you want to our example video [dancing.mp4](https://scalabel-public.s3-us-west-2.amazonaws.com/demo/dancing.mp4). 

You can use the command below to convert the video to a folder of images under `local-data/items`

```
python3 -m scalabel.tools.prepare_data --start-time 0 --max-frames 100 \
    -i dancing.mp4 -o local-data/items --fps 5 --url-root http://localhost:8686/items/
```

Please set your desired starting time and fps for annotation.

The script will also put a file named `image_list.yaml` in `local-data/items`. Then you can use this file to create a new annotation project on the project creation page. On the same page, select video as item type and segmentation as label type. More info about project creation can be found here: https://www.scalabel.ai/doc/quick-start.html

**Comment by JannisWalkKIT** [comment]
Thanks your quick answer and sorry for overlooking the /tools documentation!

When running the command you provided with my mp4 video I get the following output: 
[2020-10-10 13:59:24,911 prepare_data.py:249 prepare_data] processing 1 video(s) ...
[2020-10-10 13:59:24,914 prepare_data.py:189 create_image_list] The configuration file saved at local-data/items/image_list.yml

However, image_list.yml just contains an empty array.

Unfortunately, I can not test with your sample video, I get an "Access denied" message when following the link.

**Comment by fyu** [comment]
The video permission is fixed now. Can you share your video?

**Comment by JannisWalkKIT** [comment]
Thanks for fixing the permission! Just did a fresh installation (without utilizing Docker) and ran it with dancing.mp4 - result is still the same (besides the slightly changed output in the console):

[2020-10-12 15:50:30,298 prepare_data.py:253 prepare_data] processing 1 video(s) ...
[2020-10-12 15:50:30,300 prepare_data.py:192 create_image_list] The configuration file saved at local-data/items/image_list.yml with 0 items

Any ideas?

I can send you the video by mail in case this helps.
